//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int sno { get; set; }
        public Nullable<int> senderid { get; set; }
        public Nullable<int> receiverid { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> chattime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
